sudo: true
language: ruby
rvm:
  - 2.4.0
before_install: gem install bundler -v 1.16.0
install:
  - curl -SL https://tools.ietf.org/tools/idnits/idnits-2.15.00.tgz | tar xzv
  - sudo mv idnits-2.15.00/idnits /usr/local/bin/
  - sudo pip install -r requirements.txt
  - bundle install --path vendor/bundle
script:
  - make clean all
