[#registry-alg-hash]
= Hash Algorithms Registry

Proposed changes to the registry:

* Rename registry to "OpenPGP Hash Key Algorithms".

* Change registry policy to *Specification Required*.

* Update its "Reference" to also refer to this document.

* A Standards Track document is required to register an item
with the value "Yes" in any recommendation.

* Existing registrations with a "Reference" value pointing to a
non-IETF published document should be checked to see if an
IETF-published document is available, and if so, update the reference
to point to the IETF-published document instead for consistency.

Add the following note:

----
Note: Experts are to verify that the proposed registration
*SHOULD* provide notable benefits for the wider OpenPGP community,
and provides a publicly-available standard that can be implemented in
an interoperable way. References to IETF-published documents are
preferred. The "Reference" value should point to a document that
details the implementation of this algorithm in OpenPGP, not of
the algorithm itself.
----

Update the following registrations:

|===
| ID | Algorithm | Text Name | REC-S | REC-I | Reference

| 1   | MD5         | "MD5"       | No  | No  | <<RFC4880,9.4 of>>
| 2   | SHA-1       | "SHA1"      | No  | Yes | <<RFC4880,9.4 of>>
| 3   | RIPE-MD/160 | "RIPEMD160" | Yes |     | <<RFC4880,9.4 of>>
| 4-7 | Reserved    |             |     |     | <<RFC4880,9.4 of>>
| 8   | SHA256      | "SHA256"    | Yes | Yes | <<RFC4880,9.4 of>>
| 9   | SHA384      | "SHA384"    | Yes |     | <<RFC4880,9.4 of>>
| 10  | SHA512      | "SHA512"    | Yes | Yes | <<RFC4880,9.4 of>>
| 11  | SHA224      | "SHA224"    | Yes |     | <<RFC4880,9.4 of>>
| 12-99 | Unassigned |    | | | |
| 100-110 | Private or Experimental Use | | | | <<RFC4880,9.4 of>>
| 111-255 | Unassigned | | | |

|===

