
= Introduction

This document instructs IANA to make changes to a number of
OpenPGP-related IANA registries <<RFC4880>>. These changes were
motivated by recently proposed extensions to OpenPGP.

Modelled after <<RFC8447>>, the document
performs a similar function in modifying existing IANA registry
policies for OpenPGP <<RFC4880>>.

The changes introduced by this document are intended to be
comprehensive, proposed after a thorough review of existing registry
policy and values.  Changes include updating of registry policy,
filling in missing values, providing recommendation of registered
items and general housekeeping.

The document lists out each OpenPGP registry individually and provides
the rationale for changes and the required changes themselves.

Specifically, the following changes are pursued:

* Alignment of registry policies with <<RFC8126>>;

* Consistency of existing OpenPGP registries, for example, some
registries have the prefix "PGP" while some others don't;

* Missing values in registries while having been defined in
<<RFC4880>;

* Creating a missed registry defined in <<RFC4880>>, namely the
"OpenPGP Signature Notation Data Subpacket Flags" registry;

* A number of references in the registries point to documents that
detail a certain algorithm, but should refer to a document (and the
relevant section if appropriate) that details the implementation
requirements of that algorithm within the context of OpenPGP.

