
[#registry-spec-reg]
= Registries With The Specification Required Policy

:openpgp-list: \openpgp-reg-review@ietf.org

**Specification Required** registry requests must be submitted to 
the <<expert-pool>> through the {openpgp-list} mailing list.

The registration request will be deemed successful after three
approved <<expert-review>>, and the <<expert-pool>> will request IANA
to register the proposed registration.

== Registration Request Procedure

Registration requests sent to the mailing list for review **SHOULD**
use an appropriate subject (e.g., "Request to register value in TLS
bar registry").

Within the review period, the Designated Experts will either approve
or deny the registration request, communicating this decision to the
review list and IANA.

== Registration Request Outcome

The outcomes of a request review are:

* Approved: once there are three approved Designated Expert reviews
within the review period;

* Denied: there have been more than three Designated Expert reviews
within the review period but have not met the approval threshold of
three approvals.



