
[#registry-spec-reg]
= Registries With The "Specification Required" Policy

:openpgp-list: \openpgp-reg-review@ietf.org

Registration requests for a **Specification Required** and **Expert
Review** registry must be submitted to the Expert Pool
(<<expert-pool>>) through the {openpgp-list} mailing list.

The registration request will be deemed successful after three
approved Expert Reviews (<<expert-review>>), and the Designated
Experts will request IANA to register the proposed registration.


== Registration Request Procedure

Registration requests sent to the mailing list for review **SHOULD**
use an appropriate subject (e.g., "Registration request: new algorithm
in Symmetric Encryption registry").

Within the review period, the Designated Experts will either approve
or deny the registration request, communicating this decision to the
review list and IANA.


== Registration Request Outcome

An outcome of a registration request is determined by results of
Expert Reviews (<<expert-review>>).

A registration request is approved once it receives a minimum of three
Expert Reviews that result in approval.

The outcomes of a request review are:

* Approval: once there are three approved Designated Expert reviews
within the review period;

* Denial: there have been more than three Designated Expert reviews
within the review period but have not met the approval threshold of
three approvals.


== Temporary Registrations

To allow for the allocation of values prior to publication, Designated
Experts **MAY** approve a temporary registration once they are
satisfied that such a specification will be published. 

This temporary registration has a 1 year validity, of which when
expired will be automatically revoked. 

Once the specification that the proposal relies is published within
this period, the Designated Experts **SHOULD** request IANA to convert
this registration to an official one.

